### ISSUE TITLE
Windows Not Supported

### ISSUE THREAD

**Issue by schettn** [getcronit/pylon#32]
**Describe the bug**
Pylon does not support Windows environments. When you run `bun run dev` the following error occurs:

```bash
ERROR  [Pylon]: Couldn't build schema Could not find index.ts (pylon entrypoint)  
 at SchemaBuilder.loadSfi (Documents/company/test/pylonone/node_modules/@getcronit/pylon-builder/dist/index.js:804:13)
  at new SchemaBuilder (Documents/company/test/pylonone/node_modules/@getcronit/pylon-builder/dist/index.js:798:10)
  at Object.getTypeDefs (Documents/company/test/pylonone/node_modules/@getcronit/pylon-builder/dist/index.js:862:23)
  at buildOnce (Documents/company/test/pylonone/node_modules/@getcronit/pylon-builder/dist/index.js:24:32)
  at Bundler.build (Documents/company/test/pylonone/node_modules/@getcronit/pylon-builder/dist/index.js:111:18)
  at build2 (Documents/company/test/pylonone/node_modules/@getcronit/pylon-builder/dist/index.js:860:24)
  at Command.main (Documents/company/test/pylonone/node_modules/@getcronit/pylon-dev/dist/index.js:85:55)
  at Command.listener [as _actionHandler] (node_modules\commander\lib\command.js:542:17)
  at node_modules\commander\lib\command.js:1502:14
  at Command._chainOrCall (node_modules\commander\lib\command.js:1386:12)
 ```

This error is due to incorrect path resolving on windows inside the [pylon-builder](https://github.com/getcronit/pylon/blob/491fd3cc2b50b31b67ebb35535f50b0dcf1e42f5/packages/pylon-builder/src/schema/builder.ts#L26).

There is another issue when deleting the `.pylon` folder on re-builds inside the [pylon-builder](https://github.com/getcronit/pylon/blob/491fd3cc2b50b31b67ebb35535f50b0dcf1e42f5/packages/pylon-builder/src/bundler/bundler.ts#L79)

**To Reproduce**
1. Run `npm create pylon@latest`
2. Run `bun run dev`

**Additional context**
Many thanks to @OrelStudio for raising this issue!

**Comment by schettn** [comment]
Additional changes: 5125757000a251b84885dac8c059458f51bee823, 4f69c6ab8f4b6ae5bdd9979603ba33c58575e9f5
