### ISSUE TITLE
prisma-extended-models

### ISSUE THREAD

**Issue by kamalkech** [getcronit/pylon#57]
```
bunx prisma-extended-models generate     
error: GET https://registry.npmjs.org/prisma-extended-models - 404
```

this package deleted ?

**Comment by schettn** [comment]
Seems like the command in the docs is wrong. The correct one is `bunx prisma-repository`.

But I will remove the `prisma-extended-models` soon because they are quite outdated and might not work with the latest version of pylon.

Instead you should use [prismas client extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions/result), there you can define extra fields on your data result which is then used by pylon.

For example:

```ts
const prisma = new PrismaClient().$extends({
  name: 'code',
  result: {
    project: {
      user: {
        needs: {
          userId: true,
        },
        compute(args) {
          return async () => {
            return await prisma.user.findFirstOrThrow({
              where: {
                id: args.userId,
              },
            });
          };
        },
      }
    },
  },
});


export const graphql = {
  Query: {
    project: async (projectSlug: string) => {
      // This will also include the user relation that is only queried if needed
      return await prisma.project.findFirst({
        where: {
          slug: projectSlug,
        },
      });
    },
  },
};
```

**Comment by ckhatton-pvfscaffolding** [comment]
Ar ok! I will hardcode the relations instead.

I was about to say the command `bunx @getcronit/prisma-extended-models generate` seems to fire it up, but Prisma has since moved to v6.

Even after downgrading the Prisma and Prisma Client packages to v5, the `prisma-extended-models` still fails.

```bash
❯ bunx prisma-repository generate
Step 1: Performing yarn prisma generate
stdout: yarn run v1.22.22
$ /home/<redacted>/applications/<redacted>/node_modules/.bin/prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.22.0) to ./generated/prisma in 82ms

Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)

Tip: Easily identify and fix slow SQL queries in your app. Optimize helps you enhance your visibility: https://pris.ly/--optimize

Done in 0.91s.

stderr: 
Step 1: Prisma client generation completed
Step 2: Initializing Prisma Client and getting DMMF
Step 2: DMMF retrieval completed
Step 3: Generating repository
/home/<redacted>/applications/<redacted>/node_modules/@getcronit/prisma-extended-models/dist/cli.cjs:319
${options.dmmf.datamodel.models.map(model => {
               ^

TypeError: Cannot read properties of undefined (reading 'datamodel')
    at generateRepository (/home/<redacted>/applications/<redacted>/node_modules/@getcronit/prisma-extended-models/dist/cli.cjs:319:16)
    at Command.generate (/home/<redacted>/applications/<redacted>/node_modules/@getcronit/prisma-extended-models/dist/cli.cjs:408:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.19.3
```

**Comment by ckhatton-pvfscaffolding** [comment]
I found I have to write in this fashion to get it to work. Prisma doesn't like a returned function.

```ts
const prisma = new PrismaClient().$extends({
  name: 'code',
  result: {
    project: {
      user: {
        needs: {
          userId: true,
        },
        async compute(args) {
          return await prisma.user.findFirstOrThrow({
            where: {
              id: args.userId,
            },
          });
        },
      }
    },
  },
});
```

@schettn How would you write this if you have a singleton instance of the Prisma Client as used in the documentation?

```ts
import {PrismaClient} from '@prisma/client'
 
declare global {
  var prisma: PrismaClient | undefined
}
 
export const db = globalThis.prisma || new PrismaClient()
 
if (process.env.NODE_ENV !== 'production') globalThis.prisma = db
```

I tried doing this, but it seem to break it and there are type errors:

```ts
import {PrismaClient} from '@prisma/client'
 
declare global {
  var prisma: PrismaClient | undefined
}
 
export const db = globalThis.prisma || new PrismaClient().$extends({
  name: 'code',
  result: {
    project: {
      user: {
        needs: {
          userId: true,
        },
        async compute(args) {
          return await prisma.user.findFirstOrThrow({
            where: {
              id: args.userId,
            },
          });
        },
      }
    },
  },
})
 
if (process.env.NODE_ENV !== 'production') globalThis.prisma = db
```
